sudo: false
language: node_js

before_install:
- npm install elm

install:
- elm package install -y

script:
- elm make src/Main.elm --output src/frontend/Main.js

cache:
  directories:
    - elm-stuff/build-artifacts
