sudo: false
language: node_js

before_install:
  - npm install elm

install:
  - elm package install -y

script:
  - elm make src/Main.elm --output src/frontend/Main.js

before_deploy:
  - npm install firebase-tools

deploy:
  skip_cleanup: true
  provider: script
  script:
    - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
  on:
    branch: master

cache:
  directories:
    - elm-stuff
