sudo: false
language: node_js

before_install:
  - npm install elm uglify-js uglifycss minimize

install:
  - elm package install -y

script:
  - ./build.sh

before_deploy:
  - npm install firebase-tools

deploy:
  skip_cleanup: true
  provider: script
  script:
    - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
  on:
    branch: master

cache:
  directories:
    - elm-stuff
