sudo: false
language: node_js

before_install:
- npm install elm

install:
- elm package install -y

script:
- elm make src/Main.elm --output src/frontend/Main.js

after_success:
- npm install firebase-tools
- firebase deploy --token "$FIREBASE_TOKEN" --non-interactive

cache:
  directories:
    - elm-stuff
