sudo: false
language: node_js

before_install:
  - npm install elm uglify-js uglifycss

install:
  - elm package install -y

script:
  - elm make src/Main.elm --output src/frontend/Main.js
  - uglifyjs src/frontend/Main.js src/frontend/init.js src/frontend/native.js --compress warnings=false --no-mangle > src/public/bundle.js
  - uglifycss src/frontend/main.css > src/public/bundle.css
  - html-minifier src/frontend/index.html > src/public/index.html

before_deploy:
  - npm install firebase-tools

deploy:
  skip_cleanup: true
  provider: script
  script:
    - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
  on:
    branch: master

cache:
  directories:
    - elm-stuff
